version: "3.8"

services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: postflow
            POSTGRES_PASSWORD: zAsder!@1001
            POSTGRES_DB: postflow_db
        ports:
            - "5432:5432"
        volumes:
            - postflow_pgdata:/var/lib/postgresql/data

volumes:
    postflow_pgdata:
